#define CONNECTOR "mqtt"
#define TOPIC_TEMP "/bme/tmp/mesurements"
#define TOPIC_PRES "/bme/prs/mesurements"
#define TOPIC_HUMI "/bme/hmd/mesurements"
#define TOPIC_WIND "/hammsp/gs232"
#define TOPIC_WINDSPEED "/bme/wind/mesurements"
#define NUM_LEDS  1
#define LOOP_TIME 50
#define ANEMOMETER 4
#define WEATHERCOCK A1
#define WINDSPEED 5000
#define ALLOCATED_METEO 30000
#define ALLOCATED_WDIR 10000
#define ALLOCATED_WSPD WINDSPEED
